
CREATE TABLE TB_OWNER (
                          id     NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
                          name   VARCHAR2(255),
                          cpf    VARCHAR2(255),
                          email  VARCHAR2(255),
                          phone  VARCHAR2(255),
                          CONSTRAINT pk_owner PRIMARY KEY (id)
);

CREATE TABLE TB_CLINIC (
                           id             NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
                           name           VARCHAR2(255),
                           cnpj           VARCHAR2(255),
                           address        VARCHAR2(255),
                           phone          VARCHAR2(255),
                           opening_hours  DATE,
                           closing_hours  DATE,
                           CONSTRAINT pk_clinic PRIMARY KEY (id)
);


CREATE TABLE TB_ACCOUNT (
                            id        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
                            email     VARCHAR2(255),
                            password  VARCHAR2(255),
                            role      VARCHAR2(255),
                            owner_id  NUMBER(19),
                            clinic_id NUMBER(19),
                            CONSTRAINT pk_account PRIMARY KEY (id),
                            CONSTRAINT uq_account_owner UNIQUE (owner_id),
                            CONSTRAINT fk_account_owner FOREIGN KEY (owner_id) REFERENCES TB_OWNER (id),
                            CONSTRAINT fk_account_clinic FOREIGN KEY (clinic_id) REFERENCES TB_CLINIC (id)
);


CREATE TABLE TB_PET (
                        id          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
                        name        VARCHAR2(255),
                        species     VARCHAR2(255),
                        breed       VARCHAR2(255),
                        birth_date  DATE,
                        weight      BINARY_DOUBLE,
                        sex         NUMBER(1),
                        owner_id    NUMBER(19),
                        CONSTRAINT pk_pet PRIMARY KEY (id),
                        CONSTRAINT fk_pet_owner FOREIGN KEY (owner_id) REFERENCES TB_OWNER (id)
);


CREATE TABLE TB_APPOINTMENT (
                                id                NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
                                speciality        VARCHAR2(255),
                                symptoms          VARCHAR2(255),
                                dignosis          VARCHAR2(255),
                                observations      VARCHAR2(255),
                                appointment_date  TIMESTAMP,
                                updated_weight    BINARY_DOUBLE,
                                clinic_id         NUMBER(19),
                                pet_id            NUMBER(19),
                                CONSTRAINT pk_appointment PRIMARY KEY (id),
                                CONSTRAINT fk_appointment_clinic FOREIGN KEY (clinic_id) REFERENCES TB_CLINIC (id),
                                CONSTRAINT fk_appointment_pet FOREIGN KEY (pet_id) REFERENCES TB_PET (id)
);